// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateClipboardItem(arg1) {
  return window['go']['main']['App']['ActivateClipboardItem'](arg1);
}

export function ClearClipboardHistory() {
  return window['go']['main']['App']['ClearClipboardHistory']();
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function DeleteClipboardItem(arg1) {
  return window['go']['main']['App']['DeleteClipboardItem'](arg1);
}

export function GetBootstrapContext() {
  return window['go']['main']['App']['GetBootstrapContext']();
}

export function GetClipboardItem(arg1) {
  return window['go']['main']['App']['GetClipboardItem'](arg1);
}

export function GetConnectivityReport() {
  return window['go']['main']['App']['GetConnectivityReport']();
}

export function ListClipboardItems(arg1) {
  return window['go']['main']['App']['ListClipboardItems'](arg1);
}

export function ListOnlineDevices() {
  return window['go']['main']['App']['ListOnlineDevices']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RotateSessionToken() {
  return window['go']['main']['App']['RotateSessionToken']();
}

export function SyncClipboardItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncClipboardItem'](arg1, arg2, arg3);
}

export function UpdateClipboardItemPin(arg1, arg2) {
  return window['go']['main']['App']['UpdateClipboardItemPin'](arg1, arg2);
}
