// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {runtimeapp} from '../models';
import {auth} from '../models';

export function ActivateClipboardItem(arg1:string):Promise<store.ClipboardItemRecord>;

export function ClearClipboardHistory():Promise<number>;

export function CopyText(arg1:string):Promise<void>;

export function DeleteClipboardItem(arg1:string):Promise<void>;

export function GetBootstrapContext():Promise<runtimeapp.AppBootstrap>;

export function GetClipboardItem(arg1:string):Promise<store.ClipboardItemRecord>;

export function GetConnectivityReport():Promise<runtimeapp.ConnectivityReport>;

export function ListClipboardItems(arg1:store.ClipboardListQuery):Promise<Array<store.ClipboardItemRecord>>;

export function OpenURL(arg1:string):Promise<void>;

export function RotateSessionToken():Promise<auth.SessionSnapshot>;

export function UpdateClipboardItemPin(arg1:string,arg2:boolean):Promise<store.ClipboardItemRecord>;
