// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {auth} from '../models';
import {runtimeapp} from '../models';
import {settings} from '../models';
import {httpserver} from '../models';

export function ActivateClipboardItem(arg1:string):Promise<store.ClipboardItemRecord>;

export function ApprovePairRequest(arg1:string):Promise<auth.PairRequestSummary>;

export function ClearClipboardHistory():Promise<number>;

export function CopyText(arg1:string):Promise<void>;

export function DeleteClipboardItem(arg1:string):Promise<void>;

export function GetBootstrapContext():Promise<runtimeapp.AppBootstrap>;

export function GetClipboardItem(arg1:string):Promise<store.ClipboardItemRecord>;

export function GetConnectivityReport():Promise<runtimeapp.ConnectivityReport>;

export function GetDesktopPinned():Promise<boolean>;

export function GetDesktopSettings():Promise<settings.DesktopSettings>;

export function HideDesktopApp():Promise<void>;

export function ListClipboardItems(arg1:store.ClipboardListQuery):Promise<Array<store.ClipboardItemRecord>>;

export function ListLinkedWebDevices():Promise<Array<auth.LinkedDeviceSummary>>;

export function ListOnlineDevices():Promise<Array<httpserver.OnlineDevice>>;

export function ListPairRequests():Promise<Array<auth.PairRequestSummary>>;

export function OpenURL(arg1:string):Promise<void>;

export function ReceiveClipboardFile(arg1:string):Promise<store.ClipboardItemRecord>;

export function RejectPairRequest(arg1:string):Promise<auth.PairRequestSummary>;

export function RemoveLinkedWebDevice(arg1:string):Promise<void>;

export function RotateSessionToken():Promise<auth.SessionSnapshot>;

export function SetDesktopPinned(arg1:boolean):Promise<boolean>;

export function ShowDesktopApp():Promise<void>;

export function SyncClipboardItem(arg1:string,arg2:Array<string>,arg3:boolean):Promise<httpserver.SyncClipboardResponse>;

export function UpdateClipboardItemPin(arg1:string,arg2:boolean):Promise<store.ClipboardItemRecord>;

export function UpdateDesktopSettings(arg1:settings.DesktopSettings):Promise<settings.DesktopSettings>;
